import { theme } from '@cv/theme';
import '@fontsource/montserrat/100.css';
import '@fontsource/montserrat/300.css';
import '@fontsource/montserrat/400.css';
import '@fontsource/montserrat/500.css';
import '@fontsource/montserrat/700.css';
import '@fontsource/open-sans/300.css';
import '@fontsource/open-sans/400.css';
import '@fontsource/open-sans/500.css';
import '@fontsource/open-sans/700.css';
import { CssBaseline } from '@mui/material';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import InitColorSchemeScript from '@mui/material/InitColorSchemeScript';
import { ThemeProvider } from '@mui/material/styles';
import { Montserrat, Open_Sans } from 'next/font/google';
import './global.css';

export const metadata = {
    title: 'Welcome to langan-cv-app',
    description: 'Generated by create-nx-workspace'
};

const openSans = Open_Sans({
    weight: ['300', '400', '500', '700'],
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-open-sans'
});

const montserrat = Montserrat({
    weight: ['100', '300', '400', '500', '700'],
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-monsterrat'
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${openSans.variable} ${montserrat.variable}`}>
                <InitColorSchemeScript defaultMode="light" attribute="class" />
                <AppRouterCacheProvider
                    options={{
                        key: 'css',
                        prepend: true
                    }}
                >
                    <ThemeProvider theme={theme}>
                        <CssBaseline />
                        {/* <ModeSwitch /> */}
                        {children}
                    </ThemeProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
