import '@fontsource/open-sans/300.css';
import '@fontsource/open-sans/400.css';
import '@fontsource/open-sans/500.css';
import '@fontsource/open-sans/700.css';
import '@fontsource/montserrat/700.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import { Open_Sans, Montserrat } from 'next/font/google';
import theme from '../theme';
import './global.css';

export const metadata = {
    title: 'Welcome to langan-cv-app',
    description: 'Generated by create-nx-workspace'
};

const sourceCodePro = Open_Sans({
    weight: ['300', '400', '500', '700'],
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-open-sans'
});

const montserrat = Montserrat({
    weight: ['700'],
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-monsterrat'
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={`${sourceCodePro.variable} ${montserrat.variable}`}>
                <AppRouterCacheProvider>
                    <ThemeProvider theme={theme}>{children}</ThemeProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
