name: CI

on:
    push:
        branches:
            - main
    pull_request:

permissions:
    actions: write
    contents: write
    deployments: write

env:
    # NX release needs to have a GH token in env.GITHUB_TOKEN
    # As during this workflow we will create a new release
    # that should trigger other workflow, we need to create custom TOKEN
    # with proper permissions,
    # more: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens
    GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.PAT }}

            - uses: pnpm/action-setup@v4
              with:
                  version: 9

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'pnpm'
            - run: pnpm install --frozen-lockfile

            - uses: nrwl/nx-set-shas@v4
            - run: pnpm exec nx-cloud record -- pnpm exec nx affected -t lint test build --base=origin/main --head=HEAD

            - name: Run nx release
            - run: |
                  git config --global user.email "mr.langan@gmail.com"
                  git config --global user.name "John Langan"
                  pnpm exec nx-cloud record -- pnpm exec nx release --skip-publish
